### PR TITLE
:memo: Modify README example for session function in API Routes section

### PR DESCRIPTION
**Pull request by georgekamar**
#327

### CODE REVIEW

**Comment by hoangvvo** [comment]
That change is actually the same as before. Both of them created one session middleware. The problem arises only if one calls `session()` in multiple places, in which case  he/she should create the middleware only once and export it for other places.

Perhaps a note like: If you are going to call `session()` in multiple places, consider do it only once and export it to other places.

**Comment by georgekamar** [comment]
I had added a note, but then felt maybe I was cluttering the docs too much, Ill add one now

**Comment by georgekamar** [comment]
I added the note while keeping the example as I modified it before since I feel like users "by default" use what is in the example. Let me know if you prefer that the example be like it was previously though

**Comment by hoangvvo** [comment]
I changed it a bit. What do you think? Your modified example is okay.

**Comment by georges-cadmos** [comment]
Looks great, how did you get the checks to pass

**Comment by hoangvvo** [comment]
> Looks great, how did you get the checks to pass

Our integration test is kinda flaky so sometimes it does not pass. Don't mind the check.

**Pull request merged**
