### PR TITLE
Add parseId function

### PR DESCRIPTION
**Pull request by andreisena**
Add an optional function to parse the session ID. It can be useful to unsign session cookies from other libraries, like [express-session](https://github.com/expressjs/session).

As talked here #50.

### CODE REVIEW

**Comment by hoangvvo** [comment]
Hey @andreisena, thanks for the PR. My idea for this will be to provide both something like `options.encode` and `options.decode`.

`options.encode` will encode the serialized cookie before sending it and `options.decode` will verify the incoming cookie as well as decoding it for use.

**Comment by hoangvvo** [comment]
We will also need to do `options.encode` in https://github.com/hoangvvo/next-session/blob/master/src/session.js

**Comment by ealtunyay** [comment]
I will also look into this over the weekend if not already settled by then

**Comment by andreisena** [comment]
> Hey @andreisena, thanks for the PR. My idea for this will be to provide both something like `options.encode` and `options.decode`.

@hoangvvo Ah I see... I was using the **generateId** function to sign the token and created this **parseId** to unsign. But that would definitely be better.

@ealtunyay Thanks! That will be nice. If you need any help, I'm here! 😃

**Comment by hoangvvo** [comment]
> > Hey @andreisena, thanks for the PR. My idea for this will be to provide both something like `options.encode` and `options.decode`.
> 
> @hoangvvo Ah I see... I was using the **generateId** function to sign the token and created this **parseId** to unsign. But that would definitely be better.
> 
> > I will also look into this over the weekend if not already settled by then
> 
> @ealtunyay Thanks! That will be nice. If you need any help, I'm here!

That might do too!

**Comment by ealtunyay** [comment]
Thanks @andreisena, but I think the `encode`/`decode` options as @hoangvvo suggested is the way to go. While looking into it, `genid`/`parseId` made sense to me at first, but `genid` is meant to replace `nanoid` and should probably be left alone (The signing step is not really part of the generation step anyway). `express-session` exposes a similar `genid` option to replace `uid-safe`. Both are fine.

Looks like the id needs to be encoded in `session.js`, and decoded in `core.js`. I didn't have enough time to put together a PR but hopefully can today. Let me know if anyone has a preferred method of sharing the code/explanation

**Comment by hoangvvo** [comment]
Hey @andreisena, are you still taking on this? I or @ealtunyay can take over it if you aren't.

**Comment by hoangvvo** [comment]
Adding to @ealtunyay, we can extend this beyond simply signing/unsigning. We can also use the two methods to encrypt/decrypt the cookie using something like [hapi/iron](https://github.com/hapijs/iron)

**Comment by andreisena** [comment]
> Thanks @andreisena, but I think the `encode`/`decode` options as @hoangvvo suggested is the way to go.

I agree. The encode/decode is a more elegant solution.

> Hey @andreisena, are you still taking on this? I or @ealtunyay can take over it if you aren't.

@ealtunyay is working on it. We can close this PR.

> We can also use the two methods to encrypt/decrypt the cookie using something like [hapi/iron](https://github.com/hapijs/iron)

That would be great. You mean encrypt/decrypt by default? If so, I believe that should be optional or have a way of override it, that way we can have compatibility with other libraries.

**Comment by hoangvvo** [comment]
@andreisena Everything is optional, we can put the `encrypt` code inside the same `encode` function.

**Comment by andreisena** [comment]
> @andreisena Everything is optional, we can put the `encrypt` code inside the same `encode` function.

Perfect!

**Pull request closed without merging**
